"""Write Global Search's results window layout (30 row slots).

    python3 tools/make_globalsearch_xml.py

Each slot has a title label (2001+i), a poster list (1001+i, films and TV),
a square list (3001+i, music and podcasts) and a wide list (4001+i, YouTube's
16:9 thumbnails), all direct children of one
vertical grouplist so up/down moves between rows and hidden ones collapse.
Styled like Stremio Bridge's search results.
"""

import os

OUT = os.path.join(os.path.dirname(__file__), "..", "script.shiggsy365.globalsearch", "resources", "skins",
                   "Default", "1080i", "globalsearch-results.xml")
ROWS = 30
ACCENT = "FF12A0C7"
WHITE = "globalsearch-white.png"


def item_layout(list_id, width, height, art_w, art_h, art, focused):
    pad = 10
    parts = []
    if focused:
        parts.append(f"""                    <control type="image">
                        <left>{pad - 6}</left><top>{pad - 6}</top><width>{art_w + 12}</width><height>{art_h + 12}</height>
                        <texture colordiffuse="{ACCENT}">{WHITE}</texture>
                        <visible>Control.HasFocus({list_id})</visible>
                    </control>""")
    parts.append(f"""                    <control type="image">
                        <left>{pad}</left><top>{pad}</top><width>{art_w}</width><height>{art_h}</height>
                        <texture colordiffuse="FF1A2230">{WHITE}</texture>
                    </control>
                    <control type="image">
                        <left>{pad}</left><top>{pad}</top><width>{art_w}</width><height>{art_h}</height>
                        <aspectratio>{"keep" if art == "thumb" else "scale"}</aspectratio>
                        <texture background="true">$INFO[ListItem.Art({art})]</texture>
                    </control>
                    <control type="image">
                        <left>{pad + art_w - 34}</left><top>{pad + 6}</top><width>28</width><height>28</height>
                        <texture colordiffuse="{ACCENT}">{WHITE}</texture>
                        <visible>Integer.IsGreater(ListItem.PlayCount,0)</visible>
                    </control>
                    <control type="label">
                        <left>{pad}</left><top>{pad + art_h + 4}</top><width>{art_w}</width><height>30</height>
                        <align>center</align><font>font10</font><textcolor>{"FFFFFFFF" if focused else "FFAAAAAA"}</textcolor>
                        {"<scroll>true</scroll>" if focused else ""}
                        <label>$INFO[ListItem.Label]</label>
                    </control>""")
    tag = "focusedlayout" if focused else "itemlayout"
    return f"""                <{tag} width="{width}" height="{height}">
{chr(10).join(parts)}
                </{tag}>"""


def row_list(list_id, width, height, art_w, art_h, art):
    return f"""            <control type="list" id="{list_id}">
                <width>1800</width><height>{height}</height>
                <orientation>horizontal</orientation>
                <scrolltime>200</scrolltime>
{item_layout(list_id, width, height, art_w, art_h, art, False)}
{item_layout(list_id, width, height, art_w, art_h, art, True)}
            </control>"""


def slot(index):
    return f"""            <control type="label" id="{2001 + index}">
                <width>1800</width><height>50</height>
                <font>font13</font><textcolor>{ACCENT}</textcolor><aligny>center</aligny>
            </control>
{row_list(1001 + index, 240, 370, 220, 320, "poster")}
{row_list(3001 + index, 240, 290, 220, 220, "thumb")}
{row_list(4001 + index, 360, 250, 340, 191, "thumb")}"""


def window():
    slots = "\n".join(slot(i) for i in range(ROWS))
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Global Search results: one row per source (generated by tools/make_globalsearch_xml.py;
     filled and hidden by resources/lib/globalsearch/window.py). 1920x1080. -->
<window>
    <defaultcontrol always="true">9000</defaultcontrol>
    <animation effect="fade" time="200">WindowOpen</animation>
    <animation effect="fade" time="150">WindowClose</animation>
    <controls>
        <control type="image">
            <left>0</left><top>0</top><width>1920</width><height>1080</height>
            <texture colordiffuse="FF000000">{WHITE}</texture>
        </control>
        <control type="image">
            <left>0</left><top>0</top><width>1920</width><height>1080</height>
            <aspectratio>scale</aspectratio>
            <fadetime>300</fadetime>
            <texture background="true" colordiffuse="30FFFFFF">$INFO[ListItem.Art(fanart)]</texture>
        </control>
        <control type="image">
            <left>0</left><top>0</top><width>1920</width><height>1080</height>
            <texture colordiffuse="99102030">{WHITE}</texture>
        </control>

        <!-- Header: the search, then the focused result -->
        <control type="label" id="100">
            <left>60</left><top>25</top><width>1800</width><height>60</height>
            <font>font37</font><textcolor>FFFFFFFF</textcolor>
        </control>
        <control type="label">
            <left>60</left><top>95</top><width>1800</width><height>45</height>
            <font>font14</font><textcolor>FFFFFFFF</textcolor>
            <label>$INFO[ListItem.Label]$INFO[ListItem.Year,  [COLOR FF999999](,)[/COLOR]]$INFO[ListItem.Genre,  [COLOR FF999999]·  ,[/COLOR]]</label>
        </control>
        <control type="textbox">
            <left>60</left><top>140</top><width>1800</width><height>95</height>
            <font>font12</font><textcolor>FFCCCCCC</textcolor>
            <label>$INFO[ListItem.Plot]</label>
        </control>

        <control type="grouplist" id="9000">
            <left>60</left><top>250</top><width>1800</width><height>820</height>
            <orientation>vertical</orientation>
            <itemgap>10</itemgap>
            <scrolltime>200</scrolltime>
{slots}
        </control>
    </controls>
</window>
"""


if __name__ == "__main__":
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(window())
    print(os.path.normpath(OUT))
